name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION="$(echo $GITHUB_REF | sed -e 's:refs/tags/::')"
        else
          VERSION=0.0.0
        fi &&\
        echo VERSION=$VERSION &&\
        sudo apt-get install -y python3-venv &&\
        python3 -m venv venv &&\
        venv/bin/python3 -m pip install --upgrade pip &&\
        venv/bin/python3 -m pip install --upgrade setuptools wheel &&\
        sed -i "s/0.0.0/$VERSION/" setup.py &&\
        venv/bin/python3 setup.py sdist bdist_wheel &&\
        echo $VERSION > dist/VERSION
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
  tests:
    runs-on: ubuntu-18.04
    needs: build
    strategy:
      matrix:
        python: ["python2", "python3"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
        name: dist
    - env:
        KAMATERA_API_CLIENT_ID: ${{ secrets.KAMATERA_API_CLIENT_ID }}
        KAMATERA_API_SECRET: ${{ secrets.KAMATERA_API_SECRET }}
        PYTHON: ${{ matrix.python }}
      run: |
        if [ "${PYTHON}" == "python2" ]; then
          sudo apt-get install -y python-virtualenv &&\
          virtualenv -p python2 venv
        else
          sudo apt-get install -y $PYTHON-venv &&\
          $PYTHON -m venv venv
        fi &&\
        venv/bin/pip install --upgrade pip &&\
        venv/bin/pip install --upgrade setuptools wheel &&\
        venv/bin/pip install "apache-libcloud" &&\
        VERSION=`cat dist/VERSION` &&\
        if [ "${PYTHON}" == "python2" ]; then
          venv/bin/pip install "dist/libcloud_driver_kamatera-${VERSION}.tar.gz"
        else
          venv/bin/pip install "dist/libcloud_driver_kamatera-${VERSION}-py3-none-any.whl"
        fi &&\
        if [ "${PYTHON}" == "python3" ]; then
          export CREATE_SERVER_NAME="libcloudtest"
        else
          export CREATE_SERVER_NAME=""
        fi &&\
        venv/bin/python tests/e2e_test.py
  publish:
    runs-on: ubuntu-18.04
    needs: tests
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: dist
    - env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION="$(echo $GITHUB_REF | sed -e 's:refs/tags/::')" &&\
          echo VERSION=$VERSION &&\
          sudo apt-get install -y python3-venv &&\
          python3 -m venv venv &&\
          venv/bin/python3 -m pip install --upgrade pip &&\
          venv/bin/python3 -m pip install --upgrade twine setuptools wheel &&\
          venv/bin/twine upload --non-interactive "dist/libcloud_driver_kamatera-${VERSION}.tar.gz" "dist/libcloud_driver_kamatera-${VERSION}-py3-none-any.whl"
        fi
